export const API_ROUTE = {
  createUser: "users/",
  loginUser: "users/login",
  getAllBooks: "books/",
  getById: "books/",
  addedToCart: "carts/",
  removeFromCart: "carts/",
  addToWishList: "wishlist/",
  removeFromWishlist: "wishlist/",
  updateAddress: "users/setAddress/",
  getCart: "carts/",
  getUser: "users/",
  decreaseBookQuantity: "carts/decrease/",
  getWishlist: "wishlist/",
  highToLow: "books/highToLow",
  lowToHigh: "books/lowToHigh",
  searchBook: "books/search/",
  newArrival: "books/newArrival/",
};
